/**
 * Geographically distributed people for testing allocation planning
 * People spread across parishes to create demand nodes requiring cross-parish allocation
 */

export interface GeographicPersonSeed {
  name: string;
  type: 'person_in_need' | 'aid_worker';
  parishCode: string;
  communityName: string;
  latitude: number;
  longitude: number;
  contactName: string;
  contactPhone?: string;
  contactEmail?: string;
  needs?: string[]; // For person_in_need
  skills?: string[]; // For aid_worker
  organization?: string; // For aid_worker
  numberOfPeople?: number; // For person_in_need
}

export const geographicPeople: GeographicPersonSeed[] = [
  // People in Need - Western Jamaica
  {
    name: 'Maria Thompson',
    type: 'person_in_need',
    parishCode: 'HAN',
    communityName: 'Lucea',
    latitude: 18.4550,
    longitude: -78.1750,
    contactName: 'Maria Thompson',
    contactPhone: '876-555-1001',
    needs: ['Food', 'Water'],
    numberOfPeople: 5,
  },
  {
    name: 'Robert Brown',
    type: 'person_in_need',
    parishCode: 'WML',
    communityName: 'Savanna-la-Mar',
    latitude: 18.2200,
    longitude: -78.1350,
    contactName: 'Robert Brown',
    contactPhone: '876-555-1002',
    needs: ['Food', 'Shelter'],
    numberOfPeople: 3,
  },
  {
    name: 'Patricia Williams',
    type: 'person_in_need',
    parishCode: 'WML',
    communityName: 'Negril',
    latitude: 18.2700,
    longitude: -78.3450,
    contactName: 'Patricia Williams',
    contactPhone: '876-555-1003',
    needs: ['Water', 'Medical'],
    numberOfPeople: 2,
  },
  {
    name: 'James Johnson',
    type: 'person_in_need',
    parishCode: 'ELI',
    communityName: 'Black River',
    latitude: 18.0300,
    longitude: -77.8500,
    contactName: 'James Johnson',
    contactPhone: '876-555-1004',
    needs: ['Food', 'Water', 'Shelter'],
    numberOfPeople: 6,
  },
  {
    name: 'Sarah Davis',
    type: 'person_in_need',
    parishCode: 'ELI',
    communityName: 'Santa Cruz',
    latitude: 18.0850,
    longitude: -77.7700,
    contactName: 'Sarah Davis',
    contactPhone: '876-555-1005',
    needs: ['Food'],
    numberOfPeople: 4,
  },
  {
    name: 'Michael Wilson',
    type: 'person_in_need',
    parishCode: 'TRL',
    communityName: 'Falmouth',
    latitude: 18.4950,
    longitude: -77.6600,
    contactName: 'Michael Wilson',
    contactPhone: '876-555-1006',
    needs: ['Water', 'Hygiene'],
    numberOfPeople: 3,
  },
  {
    name: 'Jennifer Martinez',
    type: 'person_in_need',
    parishCode: 'TRL',
    communityName: 'Duncans',
    latitude: 18.4850,
    longitude: -77.7350,
    contactName: 'Jennifer Martinez',
    contactPhone: '876-555-1007',
    needs: ['Food', 'Water'],
    numberOfPeople: 7,
  },

  // People in Need - Central Jamaica
  {
    name: 'David Anderson',
    type: 'person_in_need',
    parishCode: 'ANN',
    communityName: "St. Ann's Bay",
    latitude: 18.4400,
    longitude: -77.2050,
    contactName: 'David Anderson',
    contactPhone: '876-555-1008',
    needs: ['Shelter', 'Food'],
    numberOfPeople: 4,
  },
  {
    name: 'Lisa Taylor',
    type: 'person_in_need',
    parishCode: 'ANN',
    communityName: 'Runaway Bay',
    latitude: 18.4700,
    longitude: -77.3350,
    contactName: 'Lisa Taylor',
    contactPhone: '876-555-1009',
    needs: ['Water', 'Medical'],
    numberOfPeople: 2,
  },
  {
    name: 'Christopher Lee',
    type: 'person_in_need',
    parishCode: 'CLA',
    communityName: 'May Pen',
    latitude: 17.9700,
    longitude: -77.2450,
    contactName: 'Christopher Lee',
    contactPhone: '876-555-1010',
    needs: ['Food', 'Water', 'Shelter'],
    numberOfPeople: 5,
  },
  {
    name: 'Amanda White',
    type: 'person_in_need',
    parishCode: 'CLA',
    communityName: 'Chapelton',
    latitude: 18.1200,
    longitude: -77.2200,
    contactName: 'Amanda White',
    contactPhone: '876-555-1011',
    needs: ['Food'],
    numberOfPeople: 3,
  },
  {
    name: 'Daniel Harris',
    type: 'person_in_need',
    parishCode: 'MAN',
    communityName: 'Mandeville',
    latitude: 18.0350,
    longitude: -77.5050,
    contactName: 'Daniel Harris',
    contactPhone: '876-555-1012',
    needs: ['Water', 'Shelter'],
    numberOfPeople: 4,
  },
  {
    name: 'Nicole Clark',
    type: 'person_in_need',
    parishCode: 'MAN',
    communityName: 'Christiana',
    latitude: 18.1700,
    longitude: -77.5200,
    contactName: 'Nicole Clark',
    contactPhone: '876-555-1013',
    needs: ['Food', 'Water'],
    numberOfPeople: 6,
  },
  {
    name: 'Kevin Lewis',
    type: 'person_in_need',
    parishCode: 'CAT',
    communityName: 'Spanish Town',
    latitude: 17.9950,
    longitude: -76.9600,
    contactName: 'Kevin Lewis',
    contactPhone: '876-555-1014',
    needs: ['Food', 'Shelter'],
    numberOfPeople: 3,
  },

  // Aid Workers - Distributed across parishes
  {
    name: 'Dr. Susan Green',
    type: 'aid_worker',
    parishCode: 'JAM',
    communityName: 'Montego Bay',
    latitude: 18.4780,
    longitude: -77.9200,
    contactName: 'Dr. Susan Green',
    contactPhone: '876-555-2001',
    contactEmail: 'sgreen@health.gov.jm',
    skills: ['Medical', 'Emergency Response'],
    organization: 'Ministry of Health',
  },
  {
    name: 'Mark Robinson',
    type: 'aid_worker',
    parishCode: 'WML',
    communityName: 'Savanna-la-Mar',
    latitude: 18.2220,
    longitude: -78.1340,
    contactName: 'Mark Robinson',
    contactPhone: '876-555-2002',
    skills: ['Logistics', 'Distribution'],
    organization: 'Jamaica Red Cross',
  },
  {
    name: 'Emily Foster',
    type: 'aid_worker',
    parishCode: 'ELI',
    communityName: 'Black River',
    latitude: 18.0270,
    longitude: -77.8480,
    contactName: 'Emily Foster',
    contactPhone: '876-555-2003',
    skills: ['Search & Rescue', 'First Aid'],
    organization: 'ODPEM',
  },
  {
    name: 'Thomas Moore',
    type: 'aid_worker',
    parishCode: 'ANN',
    communityName: "St. Ann's Bay",
    latitude: 18.4370,
    longitude: -77.2020,
    contactName: 'Thomas Moore',
    contactPhone: '876-555-2004',
    skills: ['Logistics', 'Coordination'],
    organization: 'Food For The Poor',
  },
  {
    name: 'Rachel King',
    type: 'aid_worker',
    parishCode: 'CLA',
    communityName: 'May Pen',
    latitude: 17.9670,
    longitude: -77.2440,
    contactName: 'Rachel King',
    contactPhone: '876-555-2005',
    skills: ['Medical', 'Nursing'],
    organization: 'Ministry of Health',
  },
  {
    name: 'Paul Scott',
    type: 'aid_worker',
    parishCode: 'MAN',
    communityName: 'Mandeville',
    latitude: 18.0340,
    longitude: -77.5010,
    contactName: 'Paul Scott',
    contactPhone: '876-555-2006',
    skills: ['Distribution', 'Transportation'],
    organization: 'Jamaica Red Cross',
  },
];

