/**
 * Geographically distributed assets for testing allocation planning
 * Assets spread across western and central Jamaica to enable realistic distance-based allocation
 */

export interface GeographicAssetSeed {
  name: string;
  type: 'food' | 'water' | 'generator' | 'hygiene_kit' | 'box_shelter';
  parishCode: string;
  communityName: string;
  latitude: number;
  longitude: number;
  quantity: number; // For warehouse_inventory
  status?: 'available' | 'deployed' | 'maintenance' | 'retired';
  organization?: string;
}

export const geographicAssets: GeographicAssetSeed[] = [
  // St. James (Montego Bay area) - Western Jamaica
  {
    name: 'Montego Bay Food Warehouse',
    type: 'food',
    parishCode: 'JAM',
    communityName: 'Montego Bay',
    latitude: 18.4762,
    longitude: -77.9189,
    quantity: 5000,
    status: 'available',
    organization: 'Jamaica Red Cross',
  },
  {
    name: 'Montego Bay Water Storage',
    type: 'water',
    parishCode: 'JAM',
    communityName: 'Montego Bay',
    latitude: 18.4800,
    longitude: -77.9100,
    quantity: 3000,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Ironshore Generator Depot',
    type: 'generator',
    parishCode: 'JAM',
    communityName: 'Ironshore',
    latitude: 18.4667,
    longitude: -77.8333,
    quantity: 15,
    status: 'available',
    organization: 'JPS',
  },
  {
    name: 'Rose Hall Hygiene Supplies',
    type: 'hygiene_kit',
    parishCode: 'JAM',
    communityName: 'Rose Hall',
    latitude: 18.4833,
    longitude: -77.8167,
    quantity: 500,
    status: 'available',
    organization: 'Ministry of Health',
  },

  // Hanover - Western Jamaica
  {
    name: 'Lucea Food Distribution Center',
    type: 'food',
    parishCode: 'HAN',
    communityName: 'Lucea',
    latitude: 18.4508,
    longitude: -78.1731,
    quantity: 3000,
    status: 'available',
    organization: 'Food For The Poor',
  },
  {
    name: 'Green Island Water Facility',
    type: 'water',
    parishCode: 'HAN',
    communityName: 'Green Island',
    latitude: 18.3667,
    longitude: -78.2000,
    quantity: 2000,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Sandy Bay Shelter Supplies',
    type: 'box_shelter',
    parishCode: 'HAN',
    communityName: 'Sandy Bay',
    latitude: 18.4167,
    longitude: -78.2167,
    quantity: 50,
    status: 'available',
    organization: 'ODPEM',
  },

  // Westmoreland - Western Jamaica
  {
    name: 'Savanna-la-Mar Food Bank',
    type: 'food',
    parishCode: 'WML',
    communityName: 'Savanna-la-Mar',
    latitude: 18.2189,
    longitude: -78.1328,
    quantity: 4000,
    status: 'available',
    organization: 'Jamaica Red Cross',
  },
  {
    name: 'Negril Water Storage',
    type: 'water',
    parishCode: 'WML',
    communityName: 'Negril',
    latitude: 18.2692,
    longitude: -78.3425,
    quantity: 2500,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Little London Generator Station',
    type: 'generator',
    parishCode: 'WML',
    communityName: 'Little London',
    latitude: 18.3000,
    longitude: -78.1500,
    quantity: 10,
    status: 'available',
    organization: 'JPS',
  },
  {
    name: 'Bluefields Hygiene Center',
    type: 'hygiene_kit',
    parishCode: 'WML',
    communityName: 'Bluefields',
    latitude: 18.1667,
    longitude: -78.0333,
    quantity: 300,
    status: 'available',
    organization: 'Ministry of Health',
  },

  // St. Elizabeth - Western Jamaica
  {
    name: 'Black River Food Warehouse',
    type: 'food',
    parishCode: 'ELI',
    communityName: 'Black River',
    latitude: 18.0253,
    longitude: -77.8464,
    quantity: 3500,
    status: 'available',
    organization: 'Food For The Poor',
  },
  {
    name: 'Santa Cruz Water Depot',
    type: 'water',
    parishCode: 'ELI',
    communityName: 'Santa Cruz',
    latitude: 18.0833,
    longitude: -77.7667,
    quantity: 2800,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Treasure Beach Emergency Supplies',
    type: 'hygiene_kit',
    parishCode: 'ELI',
    communityName: 'Treasure Beach',
    latitude: 17.9000,
    longitude: -77.7500,
    quantity: 400,
    status: 'available',
    organization: 'ODPEM',
  },
  {
    name: 'Junction Generator Facility',
    type: 'generator',
    parishCode: 'ELI',
    communityName: 'Junction',
    latitude: 18.1667,
    longitude: -77.6667,
    quantity: 12,
    status: 'available',
    organization: 'JPS',
  },

  // Trelawny - Western Jamaica
  {
    name: 'Falmouth Food Distribution',
    type: 'food',
    parishCode: 'TRL',
    communityName: 'Falmouth',
    latitude: 18.4919,
    longitude: -77.6561,
    quantity: 2500,
    status: 'available',
    organization: 'Jamaica Red Cross',
  },
  {
    name: 'Duncans Water Storage',
    type: 'water',
    parishCode: 'TRL',
    communityName: 'Duncans',
    latitude: 18.4833,
    longitude: -77.7333,
    quantity: 1800,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: "Clark's Town Shelter Materials",
    type: 'box_shelter',
    parishCode: 'TRL',
    communityName: "Clark's Town",
    latitude: 18.4167,
    longitude: -77.6000,
    quantity: 40,
    status: 'available',
    organization: 'ODPEM',
  },

  // St. Ann - Central/North Jamaica
  {
    name: "St. Ann's Bay Food Warehouse",
    type: 'food',
    parishCode: 'ANN',
    communityName: "St. Ann's Bay",
    latitude: 18.4358,
    longitude: -77.2008,
    quantity: 4500,
    status: 'available',
    organization: 'Food For The Poor',
  },
  {
    name: 'Runaway Bay Water Facility',
    type: 'water',
    parishCode: 'ANN',
    communityName: 'Runaway Bay',
    latitude: 18.4667,
    longitude: -77.3333,
    quantity: 2200,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: "Browns Town Generator Depot",
    type: 'generator',
    parishCode: 'ANN',
    communityName: 'Browns Town',
    latitude: 18.4000,
    longitude: -77.3500,
    quantity: 8,
    status: 'available',
    organization: 'JPS',
  },
  {
    name: 'Discovery Bay Hygiene Supplies',
    type: 'hygiene_kit',
    parishCode: 'ANN',
    communityName: 'Discovery Bay',
    latitude: 18.4667,
    longitude: -77.4167,
    quantity: 350,
    status: 'available',
    organization: 'Ministry of Health',
  },

  // Clarendon - Central Jamaica
  {
    name: 'May Pen Food Distribution Center',
    type: 'food',
    parishCode: 'CLA',
    communityName: 'May Pen',
    latitude: 17.9650,
    longitude: -77.2433,
    quantity: 4000,
    status: 'available',
    organization: 'Jamaica Red Cross',
  },
  {
    name: 'Chapelton Water Storage',
    type: 'water',
    parishCode: 'CLA',
    communityName: 'Chapelton',
    latitude: 18.1167,
    longitude: -77.2167,
    quantity: 2000,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Old Harbour Emergency Supplies',
    type: 'hygiene_kit',
    parishCode: 'CLA',
    communityName: 'Old Harbour',
    latitude: 17.9500,
    longitude: -77.1167,
    quantity: 450,
    status: 'available',
    organization: 'ODPEM',
  },

  // Manchester - Central Jamaica
  {
    name: 'Mandeville Food Bank',
    type: 'food',
    parishCode: 'MAN',
    communityName: 'Mandeville',
    latitude: 18.0333,
    longitude: -77.5000,
    quantity: 3000,
    status: 'available',
    organization: 'Food For The Poor',
  },
  {
    name: 'Christiana Water Depot',
    type: 'water',
    parishCode: 'MAN',
    communityName: 'Christiana',
    latitude: 18.1667,
    longitude: -77.5167,
    quantity: 1800,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Porus Generator Station',
    type: 'generator',
    parishCode: 'MAN',
    communityName: 'Porus',
    latitude: 18.0000,
    longitude: -77.3833,
    quantity: 6,
    status: 'available',
    organization: 'JPS',
  },

  // St. Catherine - Near Kingston
  {
    name: 'Spanish Town Food Warehouse',
    type: 'food',
    parishCode: 'CAT',
    communityName: 'Spanish Town',
    latitude: 17.9914,
    longitude: -76.9572,
    quantity: 5000,
    status: 'available',
    organization: 'Jamaica Red Cross',
  },
  {
    name: 'Portmore Water Facility',
    type: 'water',
    parishCode: 'CAT',
    communityName: 'Portmore',
    latitude: 17.9500,
    longitude: -76.8833,
    quantity: 3500,
    status: 'available',
    organization: 'National Water Commission',
  },
  {
    name: 'Linstead Generator Depot',
    type: 'generator',
    parishCode: 'CAT',
    communityName: 'Linstead',
    latitude: 18.1333,
    longitude: -77.0333,
    quantity: 10,
    status: 'available',
    organization: 'JPS',
  },
];

